// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package db

import (
	"context"
	"database/sql"
)

const countTodo = `-- name: CountTodo :one
select count(*)
from todo
`

func (q *Queries) CountTodo(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :execresult
insert into todo(id, title, description)
values (?, ?, ?)
`

type CreateTodoParams struct {
	ID          string         `db:"id" json:"id"`
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTodo, arg.ID, arg.Title, arg.Description)
}

const deleteTodoByID = `-- name: DeleteTodoByID :exec
delete
from todo
where id = ?
`

func (q *Queries) DeleteTodoByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTodoByID, id)
	return err
}

const getListTodo = `-- name: GetListTodo :many
select id, title, description
from todo
limit ? offset ?
`

type GetListTodoParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetListTodo(ctx context.Context, arg GetListTodoParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getListTodo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoByID = `-- name: UpdateTodoByID :exec
update todo
set title       = ?,
    description = ?
where id = ?
`

type UpdateTodoByIDParams struct {
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	ID          string         `db:"id" json:"id"`
}

func (q *Queries) UpdateTodoByID(ctx context.Context, arg UpdateTodoByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoByID, arg.Title, arg.Description, arg.ID)
	return err
}
